# Generated by Django 4.2.27 on 2026-03-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descricao',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
